#!/usr/bin/env python3
"""Download the webfonts TableX needs into TableX/fonts/ and write fonts.css.

Run this on an internet-connected machine ONLY when the font set changes; the
result is committed so the app itself never touches a CDN (the machines this
runs on have no internet).

    python tools/build_fonts.py

IBM Plex Sans Hebrew is the app's face -- it carries Plex Sans' Latin as well,
so one family serves both scripts -- and IBM Plex Mono sets the cell codes.

Inter + Heebo are kept for ONE element: the report preview (.doc-page). That
sheet is the deliverable, and it looked the way commanders know it before the
2026-09-29 redesign; the app around it changing face is no reason for it to.
Heebo carries its Hebrew because Inter has none, routed by unicode-range.
Stdlib only, like Interfex's tools/build_cell_map.py.
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), 'TableX', 'fonts')

UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')  # woff2 needs a modern UA

# family -> (file slug, the Google subset names worth shipping, weights).
# Everything else it offers (cyrillic, greek, vietnamese, Heebo's giant
# math/symbol subsets) is dead weight for a Hebrew + Latin RF tool. Match on the
# subset NAME, not on the unicode-range text: Heebo's hebrew range starts with
# U+0307-0308, so a range-prefix match silently drops every Hebrew face.
FAMILIES = {
    'IBM Plex Sans Hebrew': ('plex', ['hebrew', 'latin'], '400;500;600'),
    'IBM Plex Mono':        ('plexmono', ['latin'], '400;500'),
    'Inter':                ('inter', ['latin', 'latin-ext'], '400;500;600'),
    'Heebo':                ('heebo', ['hebrew'], '400;500;600'),
}


def fetch(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={'User-Agent': UA})).read()


def main():
    os.makedirs(OUT, exist_ok=True)
    faces = []

    for family, (slug, wanted, weights) in FAMILIES.items():
        api = ('https://fonts.googleapis.com/css2?family=%s:wght@%s&display=swap'
               % (family.replace(' ', '+'), weights.replace(';', '%3B')))
        css = fetch(api).decode('utf8')

        # Each @font-face is preceded by a /* subset-name */ comment.
        for m in re.finditer(r'/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}', css, re.S):
            subset, body = m.group(1), m.group(2)
            if subset not in wanted:
                continue
            rng = re.search(r'unicode-range:\s*([^;]+);', body).group(1).strip()
            weight = re.search(r'font-weight:\s*(\d+)', body).group(1)
            url = re.search(r'url\((https://[^)]+\.woff2)\)', body).group(1)
            name = '%s-%s-%s.woff2' % (slug, subset, weight)
            with open(os.path.join(OUT, name), 'wb') as fh:
                fh.write(fetch(url))
            faces.append((family, weight, name, rng))

    if not faces:
        sys.exit('No faces matched - Google may have renamed its subsets.')

    out = ['/* GENERATED by tools/build_fonts.py -- do not hand-edit.',
           ' * Self-hosted: these machines have no internet, so no CDN link.',
           ' * IBM Plex Sans Hebrew is the app (both scripts), IBM Plex Mono the',
           ' * codes. Inter + Heebo set the report preview only (.doc-page);',
           ' * unicode-range routes each script to its own face. */', '']
    for family, weight, name, rng in faces:
        out += ['@font-face {',
                "  font-family: '%s';" % family,
                '  font-style: normal;',
                '  font-weight: %s;' % weight,
                '  font-display: swap;',
                "  src: url('%s') format('woff2');" % name,
                '  unicode-range: %s;' % rng,
                '}']
    with open(os.path.join(OUT, 'fonts.css'), 'w', encoding='utf8') as fh:
        fh.write('\n'.join(out) + '\n')

    total = 0
    for family, weight, name, _ in faces:
        size = os.path.getsize(os.path.join(OUT, name))
        total += size
        print('%-34s %s  %7d B' % (name, weight, size))
    print('%-34s    %7d B  (%d files)' % ('TOTAL', total, len(faces)))


if __name__ == '__main__':
    main()
